Question - 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as n
a=n.arange(2,50,3)
a

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

Question - 2
Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [13]:
a=[]
b=[]
for j in range(5):
    a.append(int(input()))
for h in range(5):
    b.append(int(input()))
a=n.array(a)
b=n.array(b)
a=n.concatenate((a,b))
a.sort()
print(a)

7
6
5
5
5
5
5
6
6
7
[5 5 5 5 5 6 6 6 7 7]


Question - 3:
Write a code snippet to find the dimensions of a ndarray and its size

In [11]:
a=n.array([[2,3,5],[5,6,3]])

print(a.ndim)
print(a.size)

2
6


Question - 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [15]:
a=n.array([1,2,3,4,5,6,7,8,9,10])
a=n.reshape(a,(2,5))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.

In [21]:
a=n.array([[1,2,3],[4,5,6]])
b=n.array([[4,5,6],[1,2,3]])
print(n.vstack((a,b)))
print(n.hstack((a,b)))

[[1 2 3]
 [4 5 6]
 [4 5 6]
 [1 2 3]]
[[1 2 3 4 5 6]
 [4 5 6 1 2 3]]


Questions 6:
How to get unique items and counts of unique items?

In [34]:
a=n.array([1,2,3,4,2,3,6,5,2,3,6,5,8,9,63,1,4,5,2,6,25,2,5,2,5255,5254])
u,counts=n.unique(a,return_counts=True)
a = n.asarray((u, counts)).T
print(a)

[[   1    2]
 [   2    6]
 [   3    3]
 [   4    2]
 [   5    4]
 [   6    3]
 [   8    1]
 [   9    1]
 [  25    1]
 [  63    1]
 [5254    1]
 [5255    1]]
